model:
    cutoff: 4.0
    chemical_species: 'Hf, O'
    channel: 4
    radial_basis:
        radial_basis_name: 'bessel'
        bessel_basis_num: 8
    lmax: 2
    num_convolution_layer: 1

train:
    epoch: 300
    optimizer: 'adam'
    optim_param:
        lr: 0.005
    scheduler: 'exponentiallr'
    scheduler_param:
        gamma: 0.99

    skip_output_until: 3
    draw_learning_curve: True

    output_per_epoch: 
        per_epoch: 2
        save_data_pickle: True
        draw_parity: False
        deploy_model: True
        model_check_point: True

data:
    #structure_list: './HfO2_raw_data/structure_list_small'
    load_dataset_path: 'test/saved_dataset.pt'
