model:
    cutoff: 4.0
    chemical_species: 'Hf, O'
    channel: 4
    radial_basis:
        radial_basis_name: 'bessel'
        bessel_basis_num: 8
    lmax: 2
    num_convolution_layer: 1

train:
    epoch: 10
    optimizer: 'adam'
    optim_param:
        lr: 0.005
    scheduler: 'exponentiallr'
    scheduler_param:
        gamma: 0.99

    skip_output_until: 3
    draw_learning_curve: True

    output_per_epoch: 
        per_epoch: 5
        save_data_pickle: False
        draw_parity: True  # note that this is expensive
        deploy_model: True
        model_check_point: False
    is_train_stress: False  # True by default

data:
    batch_size: 2
    save_dataset_path: 'total' #path or filename to save total dataset
    #save_by_label: True
    structure_list: './structure_list'
    #load_dataset_path: './total.sevenn_data'
